name: fruit_collector
description: "A new Flutter project with Flame."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  window_size: ^0.1.0
  flame: ^1.28.1
  flame_tiled: ^3.0.2
  flame_audio: ^2.11.5
  syncfusion_flutter_sliders: ^29.2.4
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.5
  sqlite3_flutter_libs: ^0.5.32
  path: ^1.8.3
  font_awesome_flutter: ^10.8.0
  just_audio: ^0.10.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  fonts:
    - family: ArcadeClassic
      fonts:
        - asset: assets/fonts/ArcadeClassic.ttf
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/gifsMainMenu/
    - assets/tiles/
    - assets/images/Gems/
    - assets/images/Terrain/
    - assets/images/difficulty/
    - assets/images/GUI/HUD/
    - assets/images/Items/Fruits/
    - assets/images/Items/Boxes/Box2/
    - assets/images/Items/Checkpoints/Checkpoint/
    - assets/images/Items/Checkpoints/End/
    - assets/images/Traps/Saw/
    - assets/images/Traps/Spike Head/
    - assets/images/Traps/Falling Platforms/
    - assets/images/Traps/Spikes/
    - assets/images/Main Characters/
    - assets/images/Terrain/
    - assets/images/Background/
    - assets/images/Main Characters/Mask Dude/
    - assets/images/Main Characters/Ninja Frog/
    - assets/images/Main Characters/Pink Man/
    - assets/images/Main Characters/Virtual Guy/
    - assets/images/Main Characters/1/
    - assets/images/Main Characters/2/
    - assets/images/Main Characters/3/
    - assets/images/Enemies/Chicken/
    - assets/images/Enemies/Radish/
    - assets/images/Enemies/Rocks/
    - assets/images/Enemies/Bee/
    - assets/images/Enemies/Ghost/
    - assets/images/Enemies/Snail/
    - assets/images/Traps/Trampoline/
    - assets/images/Traps/Fan/
    - assets/images/Traps/Fire/
    - assets/images/Trophys/
    - assets/icon/
    - assets/images/loadingBanana/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true